- name: Assert that scrape targets are defined
  ansible.builtin.assert:
    that:
      - "'scrape_configs' in vars"
    msg: You must define scrape_configs in file scrape_configs.yml within the root folder of this project.  See README.md for instructions.
  tags:
    - scrape_configs
- name: Deploy the targets to probe
  k8s:
    kubeconfig: "{{ k3s_config_file }}"
    context: default
    state: present
    template: ../definitions/prometheus-scrape-targets.yml.j2
  tags:
    - scrape_configs
