# https://docs.k3s.io/installation/requirements?os=debian
- block:
    - name: Deploy the Prometheus Operator
      k8s:
        kubeconfig: "{{ k3s_config_file }}"
        context: default
        state: present
        definition: >-
          {{ lookup('file', '../definitions/prometheus-operator.yml') | from_yaml_all }}
    - name: Deploy the observability stack Prometheus objects
      k8s:
        kubeconfig: "{{ k3s_config_file }}"
        context: default
        state: present
        definition: >-
          {{ lookup('file', '../definitions/prometheus-crds.yml') | from_yaml_all }}
    - name: Deploy self-monitoring for Prometheus and its operator
      k8s:
        kubeconfig: "{{ k3s_config_file }}"
        context: default
        state: present
        definition: >-
          {{ lookup('file', '../definitions/prometheus-servicemonitors.yml') | from_yaml_all }}
    - name: Test that Prometheus is up
      uri:
        url: http://localhost:32090/graph
      register: prometheus_up_check
      until: "'status' in prometheus_up_check and prometheus_up_check.status == 200"
      # Checks fail in check mode.
      when: not ansible_check_mode
      retries: 24
      delay: 5
  tags:
    - prometheus
