- name: Set up Minikube user
  ansible.builtin.user:
    name: minikube
    comment: Minikube system user
    group: docker
    system: true
    home: /var/lib/minikube
    shell: /bin/bash
    create_home: true
- name: Set up Docker driver
  shell:
    cmd: |-
      driver=$(sudo -i -u minikube minikube config get driver || true)
      if [ "$driver" != "docker" ]
      then
        sudo -i -u minikube minikube config set driver docker
        echo changed=yes
      fi
    # We must use sudo because become: fails with permission errors.
    warn: false
  register: docker_driver
  changed_when: >-
    "changed=yes" in docker_driver.stdout
- name: Gather status of Minikube
  shell:
    cmd: sudo -i -u minikube minikube status || true
    warn: false
  check_mode: false
  register: minikube_status
  changed_when: false
- name: Start Minikube
  shell:
    cmd: sudo -i -u minikube minikube start
    warn: false
  when: >-
    "Nonexistent" in minikube_status.stdout
    or "not found" in minikube_status.stdout
- name: Test Minikube
  shell:
    cmd: sudo -i -u minikube minikube status
    warn: false
  changed_when: false
  register: minikube_status
- name: Update Minikube kubectl context
  shell:
    cmd: sudo -i -u minikube minikube update-context
    warn: false
  when: >-
    "stale minikube-vm" in (minikube_status.stdout + minikube_status.stderr)
