- name: Install virt-manager
  when: ansible_facts["os_family"] == "Debian" or ansible_facts["distribution"] == "Fedora"
  ansible.builtin.package:
    name: virt-manager
    state: present
  become: true
  become_user: root

- name: Fail on unsupported distribution
  when: not (ansible_facts["os_family"] == "Debian" or ansible_facts["distribution"] == "Fedora")
  shell: "Your operating system is not supported.  Please install Vagrant on your system using the method documented by the Vagrant project."
