- name: Fail on unsupported distribution
  ansible.builtin.fail:
    msg: "Your operating system is not supported.  Please install Vagrant on your system using the method documented by the Vagrant project."
  when: >-
    not (ansible_facts["os_family"] == "Debian" or ansible_facts["distribution"] == "Fedora" or ansible_facts["os_family"] == "Darwin")

- name: Install Helm on Linux systems
  when: ansible_facts["os_family"] == "Debian" or ansible_facts["distribution"] == "Fedora"
  block:
    - name: Retrieve Helm installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /usr/local/bin/get-helm.sh
      register: helm_installer
    - name: Run Helm installer
      ansible.builtin.shell:
        cmd: |
          which helm && exit 0 || true
          bash /usr/local/bin/get-helm.sh || exit $?
          echo INSTALLED
      register: helm_installation
      changed_when: >-
        "INSTALLED" in helm_installation.stdout

- name: Install Helm on Mac OS X
  when: ansible_facts["os_family"] == "Darwin"
  block:
    - community.general.homebrew_cask:
        name: helm
        state: present

- name: Install Helm diff plugin
  ansible.builtin.shell:
    cmd: |
      helm plugin list | grep ^diff || {
        helm plugin install https://github.com/databus23/helm-diff || exit $?
        echo INSTALLED
      }
  register: helm_diff
  changed_when: >-
    "INSTALLED" in helm_diff.stdout
