# https://docs.k3s.io/installation/requirements?os=debian
- block:
    - name: Instruct ufw to allow connections to Prometheus
      community.general.ufw:
        rule: allow
        port: "32090"
        proto: tcp
  when: ansible_facts["os_family"] == "Debian"
- block:
    - name: Instruct firewalld to allow connections to Prometheus
      ansible.posix.firewalld:
        permanent: true
        state: enabled
        port: "32090/tcp"
  when: ansible_facts["distribution"] == "Fedora"
