# https://docs.k3s.io/installation/requirements?os=debian
- block:
    - name: Instruct ufw to allow connections to Prometheus
      community.general.ufw:
        rule: allow
        port: "32090"
        proto: tcp
  when: ansible_facts["os_family"] == "Debian"
- block:
    - fail:
        msg: This distribution ({{ ansible_facts["os_family"] }}) is not supported.
  when: ansible_facts["os_family"] != "Debian"
