- name: Ensure NAT network IPv6 is deployed to VirtualBox
  shell:
    cmd: |
      vboxmanage natnetwork list | grep -q IPv6 || {
            vboxmanage natnetwork add --netname IPv6 --ipv6-enable on --ipv6-default on --network 192.168.55.0/24 || exit $?
            echo CHANGED
      }
  register: ipv6_natnetwork
  changed_when: >-
    "CHANGED" in ipv6_natnetwork.stdout
