- hosts: all
  tasks:
    - name: Ensure systemd-resolved dropin directory exists
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
    - name: Allow resolver to listen on IPv6
      ansible.builtin.copy:
        content: |
          [Resolve]
          DNSStubListenerExtra=[::1]:53
        dest: /etc/systemd/resolved.conf.d/stub-ip6.conf
      notify: Restart systemd-resolved
    - name: Install net-tools
      ansible.builtin.package:
        name: net-tools
        state: present
    - name: Ensure there is at least a bit of swap
      ansible.builtin.shell:
        cmd: |
          set -e
          size=0
          if test -f /var/swap
          then
            size=$(stat --format=%s /var/swap)
          fi
          if [ "$size" != "2147483648" ]
          then
            swapoff /var/swap || true
            dd if=/dev/zero of=/var/swap bs=1M count=2048
            mkswap /var/swap
            swapon /var/swap
            echo CHANGED
          fi
      register: swap
      changed_when: >-
        "CHANGED" in swap.stdout
    - name: Ensure swap is enabled on boot
      ansible.posix.mount:
        src: /var/swap
        path: none
        fstype: swap
        state: present
  handlers:
    - name: Restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
