VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/jammy64"
  # Use config.vm.box = "alvistack/fedora-39" for Fedora.
  config.disksize.size = '50GB'

  config.vm.provider :virtualbox do |v|
    v.name = "observability"
    v.memory = 3600
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--nic2", "natnetwork"]
    v.customize ["modifyvm", :id, "--nat-network2", "IPv6"]
  end

  config.vm.hostname = "observability"
  config.vm.network :private_network, ip: "192.168.56.42"
  config.vm.network "forwarded_port", guest: 32090, host: 32090
  config.vm.network "forwarded_port", guest: 32091, host: 32091

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :observability do |observability|
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provisioning.yml"
    ansible.become = true
  end

end