{
 "title": "Node Provider Rewards Dashboard",
 "tags": [
  "node-rewards",
  "provider",
  "rewards",
  "performance"
 ],
 "time": { "from": "2025-11-13T00:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "provider",
    "label": "Provider",
    "query": {
     "query": "label_values(nodes_count, provider_id)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(original_failure_rate{provider_id=~\"$provider\"}, node_id)"
    }
   },
   { "name": "Filters" },
   { "name": "scale_xdrp_to_xdr", "query": "10000" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "## Node Rewards Dashboard Investigation Guide\n\nWhen investigating a reward period, use the **Grafana Date Picker** to select the precise date range that *fully covers* the reward window.\n\n### Why This Is Important  \nReward metrics are stored at **00:00:00 UTC**, meaning:\n\n- Using relative ranges like `Last X days` may **exclude the first day** of the period.\n- Always double-check your selected range when reviewing a current or past reward period.\n\n### Exporting Reward Data  \n- To export data in CSV format, you can use the **DRE tool**, available here:  \n  https://github.com/dfinity/dre/latest\n- Instructions on how to use the tool:  \n  https://dfinity.github.io/dre/node-rewards.html?h=node+rewa\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "### What this dashboard shows\n- How rewards are affected over a selected date range.\n- Which node/nodes concurred to possible rewards reductions over the date range.\n\n### How to investigate\n\n#### Example: 2025‑11 distribution\n1. Open the date picker and set From = 2025‑10‑14, To = 2025‑11‑12.\n2. Pick the Node Provider of interest.\n3. For an Node Provider:\n   - Check `Base vs Adjusted rewards over time` and `Provider rewards penalty` to see when the gap opens.\n   - Open `Performance multiplier` to see which nodes drove the drop.\n   - Correlate with `Original failure rate` and `Relative failure rate`.\n     - If relative ≈ original, it’s node‑specific issue.\n     - If relative ≈ 0 while original is high, the subnet likely had issues. Rewards won't be impacted.\n   - Validate with `Subnet failure rates over time`.\n\n#### Example:“Current distribution\n1. In the date picker, set:\n   - **From** = the date shown in `Current Reward Period Start`.\n   - **To** = today.\n2. Repeat the analysis steps above to identify current drivers.\n"
   }
  },
  {
   "title": "Current Reward Period Start",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "governance_latest_reward_event_timestamp_seconds * 1000"
    }
   ]
  },
  {
   "title": "Total Reward Reduction",
   "type": "stat",
   "description": "(1 - Total Adjusted Rewards / Total Base Rewards) * 100",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(sum_over_time(total_adjusted_rewards_xdr_permyriad[$__range])) / sum(sum_over_time(total_base_rewards_xdr_permyriad[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "Total Adjusted Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(total_adjusted_rewards_xdr_permyriad[$__range])) / ${scale_xdrp_to_xdr}"
    }
   ]
  },
  {
   "title": "Total Base Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(total_base_rewards_xdr_permyriad[$__range])) / ${scale_xdrp_to_xdr}"
    }
   ]
  },
  {
   "title": "Rewards Per Provider",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (provider_id) (sum_over_time(total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}[$__range])) / ${scale_xdrp_to_xdr}"
    },
    {
     "expr": "sum by (provider_id) (sum_over_time(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"}[$__range])) / ${scale_xdrp_to_xdr}"
    },
    {
     "expr": "(sum by (provider_id) (sum_over_time(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"}[$__range])) - sum by (provider_id) (sum_over_time(total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}[$__range]))) / ${scale_xdrp_to_xdr}"
    },
    {
     "expr": "(sum by (provider_id) (sum_over_time(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"}[$__range])) / sum by (provider_id) (sum_over_time(total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}[$__range]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Provider Rewards Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Base vs Adjusted Rewards ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "XDR" } },
   "targets": [
    {
     "expr": "total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"} / ${scale_xdrp_to_xdr}",
     "legendFormat": "Base - {{provider_id}} "
    },
    {
     "expr": "total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"} / ${scale_xdrp_to_xdr}",
     "legendFormat": "Adjusted - {{provider_id}}"
    }
   ]
  },
  {
   "title": "Provider Rewards Penalty (Base - Adjusted)",
   "type": "timeseries",
   "description": "Rewards penalty/loss per provider (Base - Adjusted)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "XDR" } },
   "targets": [
    {
     "expr": "(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"} - total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"} ) / ${scale_xdrp_to_xdr}",
     "legendFormat": "Penalty - {{provider_id}}"
    }
   ]
  },
  {
   "title": "Node Counts Over Time",
   "type": "timeseries",
   "description": "Node counts over time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodes_count{provider_id=~\"$provider\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "count(original_failure_rate{provider_id=~\"$provider\"})",
     "legendFormat": "Assigned"
    }
   ]
  },
  {
   "title": "Rewards %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"} / total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}",
     "legendFormat": "{{provider_id}}"
    }
   ]
  },
  { "title": "Node-Level Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Performance Multiplier - All Nodes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(performance_multiplier{provider_id=~\"$provider\",node_id=~\"$node\"}, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  {
   "title": "Node Original Failure Rate - Assigned",
   "type": "timeseries",
   "description": "Original failure rate by node",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(original_failure_rate{provider_id=~\"$provider\",node_id=~\"$node\"}, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  {
   "title": "Node Relative Failure Rate - Assigned",
   "type": "timeseries",
   "description": "Relative failure rate by node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(relative_failure_rate{provider_id=~\"$provider\",node_id=~\"$node\"}, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  {
   "title": "Original Failure Rate Heatmap",
   "type": "heatmap",
   "description": "Heatmap showing distribution of original failure rates across all nodes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "label_replace(original_failure_rate{provider_id=~\"$provider\", node_id=~\"$node\"}, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  {
   "title": "Relative Failure Rate Heatmap",
   "type": "heatmap",
   "description": "Heatmap showing distribution of relative failure rates across all nodes.\nrelative failure rate = original failure rate - subnet failure rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "label_replace(relative_failure_rate{provider_id=~\"$provider\", node_id=~\"$node\"}, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  { "title": "Subnet Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Subnet Failure Rates Over Time",
   "type": "timeseries",
   "description": "Subnet failure rates over time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "subnets_failure_rate", "legendFormat": "{{subnet_id}}" }
   ]
  }
 ]
}