---
# Namespace for the observability stack objects.
# Replicated in prometheus-crds.yml.
apiVersion: v1
kind: Namespace
metadata:
  name: observability-stack
---
# Grafana application.
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: observability-stack
  labels:
    app: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    dashboards: "observability-stack"
spec:
  deployment:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: grafana
            app.kubernetes.io/instance: grafana
  config:
    log:
      mode: "console"
    security:
      # FIXME.
      admin_user: root
      admin_password: password
---
# Grafana service exposed to public.
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability-stack
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - name: grafana-http
      nodePort: 32091
      port: 3000
      protocol: TCP
      targetPort: grafana-http
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
# FIXME persistent storage for Grafana settings
# FIXME data sources for Grafana.
