---
# Monitor the Grafana Operator itself.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: observability-stack
  name: grafana-operator-metrics-service
  labels:
    app: grafana
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-operator
  namespaceSelector:
    any: true
---
# Monitor instances of Grafana external services.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: observability-stack
  name: grafana
  labels:
    app: grafana
spec:
  endpoints:
    - interval: 30s
      port: grafana-http
  selector:
    matchLabels:
      app: grafana
