---
# Grafana IC Metrics data source
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: ic-metrics
  namespace: observability-stack
  labels:
    app: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "observability-stack"
  datasource:
    name: IC Metrics (cluster local)
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
