# Service account (necessary).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-discovery
  namespace: observability-stack
  labels:
    app.kubernetes.io/name: service-discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/instance: service-discovery
    app.kubernetes.io/name: service-discovery
  name: service-discovery
  namespace: observability-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: Aggregator
      app.kubernetes.io/instance: service-discovery
      app.kubernetes.io/name: service-discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/component: Aggregator
        app.kubernetes.io/instance: service-discovery
        app.kubernetes.io/name: service-discovery
    spec:
      containers:
        - image: ghcr.io/dfinity/dre/multiservice-discovery:e00f95d876050cbb08f0f320ad6ba1ca0cf6442b
          imagePullPolicy: IfNotPresent
          name: service-discovery
          ports:
            - containerPort: 8000
              name: server
              protocol: TCP
          args:
            - --targets-dir
            - /tmp
            - --networks-state-file
            - /tmp/definitions.json
      serviceAccountName: service-discovery
      terminationGracePeriodSeconds: 60
---
# Service exposed to public.
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: observability-stack
  labels:
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/instance: service-discovery
    app.kubernetes.io/name: service-discovery
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 32080
      port: 8000
      protocol: TCP
      targetPort: server
  selector:
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/instance: service-discovery
    app.kubernetes.io/name: service-discovery
---
# Monitor instances of Grafana external services.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-discovery
  namespace: observability-stack
  labels:
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/instance: service-discovery
    app.kubernetes.io/name: service-discovery
spec:
  endpoints:
    - interval: 30s
      port: server
  selector:
    matchLabels:
      app.kubernetes.io/name: service-discovery
