- name: Deploy the observability stack onto the node
  hosts: observability
  become: true
  vars_files:
    - ../../vars/software.yml
  tasks:
    - import_tasks: ../../tasks/setup-k3s-reqs.yml
    - import_tasks: ../../tasks/deploy-k3s-cluster.yml
