- name: Provision the system
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
        - block:
                - include_tasks: ../../tasks/setup-virtualbox-natnetwork-ipv6.yml
                - include_tasks: ../../tasks/provision-vagrant-ubuntu.yml
          when: hostvars["observability"].get("ansible_connection", "ssh") == "vagrant"
