- name: Provision the system
  hosts: localhost
  connection: local
  tasks:
        - block:
                - shell:
                        cmd: |
                              vboxmanage natnetwork list | grep -q IPv6 || {
                                    vboxmanage natnetwork add --netname IPv6 --ipv6-enable on --ipv6-default on --network 192.168.55.0/24 || exit $?
                                    echo CHANGED
                              }
                  register: ipv6_natnetwork
                  changed_when: >-
                        "CHANGED" in ipv6_natnetwork.stdout
                - include_tasks: ../../tasks/provision-vagrant-ubuntu.yml
          when: hostvars["observability"]["ansible_connection"] == "vagrant"

- name: Test the provisioned system
  hosts: observability
  gather_facts: false
  tasks:
        - name: Test IPv6 connectivity on machine
          ansible.builtin.shell:
                cmd: |
                      set -e
                      >&2 echo Testing dig of ic0.app
                      dig -6 ic0.app AAAA
                      >&2 echo Testing ping of ic0.app
                      ping -c2 -6 ic0.app
          changed_when: false
          check_mode: false
