- name: Setup target scraping in the stack
  hosts: observability
  collections:
    - kubernetes.core
  vars_files:
    - ../../vars/k3s.yml
    - ../../vars/scrape_profiles.yml
    - ../../vars/scrape_configs.yml
    - ../../scrape_configs.yml
  become: true
  tasks:
    - import_tasks: ../../tasks/configure-service-discovery.yml
    - import_tasks: ../../tasks/configure-scrape-targets.yml
