- name: Test the system is compatible
  hosts: observability
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - block:
        - fail:
            msg: Distribution {{ ansible_facts["distribution"] }} is not supported
      when: >-
        ansible_facts["os_family"] != "Debian" and ansible_facts["distribution"] != "Fedora"
    - include_tasks: ../../tasks/test-ipv6-connectivity.yml
    - name: Update all packages to their latest version
      ansible.builtin.package:
        name: "*"
        state: latest
        update_cache: yes
      register: upgrade
    - name: Reboot after upgrades
      ansible.builtin.raw: systemd-run --on-active=1 systemctl reboot
      when: upgrade.changed
      register: reboot
    - name: Wait for machine to return
      ansible.builtin.wait_for_connection:
        delay: 30
        sleep: 3
        timeout: 600
      when: reboot.changed
    - name: Keystone check
      shell: whoami
      changed_when: false
    - include_tasks: ../../tasks/test-ipv6-connectivity.yml
