{
 "title": "Node Provider Rewards Dashboard",
 "tags": [
  "node-rewards",
  "provider",
  "rewards",
  "performance"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "provider",
    "label": "Provider",
    "query": {
     "query": "label_values(nodes_count, provider_id)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(original_failure_rate{provider_id=~\"$provider\"}, node_id)"
    }
   },
   {
    "name": "subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(subnet_failure_rate, subnet_id)"
    }
   },
   {
    "name": "days_since_last_distribution",
    "query": {
     "query": "query_result(last_over_time(days_since_governance_distribution[35d]))"
    }
   },
   { "name": "Filters" },
   { "name": "scale_xdrp_to_xdr", "query": "10000" }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "Total nodes across all providers",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nodes_count)" }
   ]
  },
  {
   "title": "Total Providers",
   "type": "stat",
   "description": "Total number of providers tracked",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "count(nodes_count)" }
   ]
  },
  { "title": "Current Reward Period", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Start Reward Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "governance_latest_reward_event_timestamp_seconds * 1000"
    }
   ]
  },
  {
   "title": "Total Base Rewards",
   "type": "stat",
   "description": "Total base rewards across all providers (XDR Permyriad)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(total_base_rewards_xdr_permyriad[${days_since_last_distribution}d])) / ${scale_xdrp_to_xdr}"
    }
   ]
  },
  {
   "title": "Total Adjusted Rewards",
   "type": "stat",
   "description": "Total adjusted rewards across all providers ",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(total_adjusted_rewards_xdr_permyriad[${days_since_last_distribution}d])) / ${scale_xdrp_to_xdr}"
    }
   ]
  },
  {
   "title": "Rewards Efficiency %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(total_adjusted_rewards_xdr_permyriad[${days_since_last_distribution}d])) / sum(sum_over_time(total_base_rewards_xdr_permyriad[${days_since_last_distribution}d])) * 100"
    }
   ]
  },
  {
   "title": "Rewards Per Provider",
   "type": "table",
   "description": "Comprehensive provider metrics overview",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (provider_id) (sum_over_time(total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}[${days_since_last_distribution}d])) / ${scale_xdrp_to_xdr}"
    },
    {
     "expr": "sum by (provider_id) (sum_over_time(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"}[${days_since_last_distribution}d])) / ${scale_xdrp_to_xdr}"
    },
    {
     "expr": "(sum by (provider_id) (sum_over_time(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"}[${days_since_last_distribution}d])) - sum by (provider_id) (sum_over_time(total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}[${days_since_last_distribution}d]))) / ${scale_xdrp_to_xdr}"
    },
    {
     "expr": "(sum by (provider_id) (sum_over_time(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"}[${days_since_last_distribution}d])) / sum by (provider_id) (sum_over_time(total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}[${days_since_last_distribution}d]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Provider Rewards Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Base vs Adjusted Rewards Over Time",
   "type": "timeseries",
   "description": "Base vs Adjusted rewards over time for selected provider(s)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}",
     "legendFormat": "Base - {{provider_id}} "
    },
    {
     "expr": "total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"}",
     "legendFormat": "Adjusted - {{provider_id}}"
    }
   ]
  },
  {
   "title": "Provider Rewards Efficiency Over Time",
   "type": "timeseries",
   "description": "Rewards efficiency percentage (Adjusted/Base * 100)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"} / total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"}) * 100",
     "legendFormat": "{{provider_id}} - Efficiency %"
    }
   ]
  },
  {
   "title": "Node Counts Over Time",
   "type": "timeseries",
   "description": "Node counts over time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodes_count{provider_id=~\"$provider\"} offset -1d",
     "legendFormat": "{{provider_id}} - Total Nodes"
    }
   ]
  },
  {
   "title": "Provider Rewards Penalty (Base - Adjusted)",
   "type": "timeseries",
   "description": "Rewards penalty/loss per provider (Base - Adjusted)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(total_adjusted_rewards_xdr_permyriad{provider_id=~\"$provider\"} - total_base_rewards_xdr_permyriad{provider_id=~\"$provider\"} )",
     "legendFormat": "{{provider_id}} - Penalty"
    }
   ]
  },
  { "title": "Node-Level Metrics (Assigned)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Node Original Failure Rate",
   "type": "timeseries",
   "description": "Original failure rate by node",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(original_failure_rate{provider_id=~\"$provider\",node_id=~\"$node\"} offset -1d, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  {
   "title": "Node Relative Failure Rate",
   "type": "timeseries",
   "description": "Relative failure rate by node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(relative_failure_rate{provider_id=~\"$provider\",node_id=~\"$node\"} offset -1d, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  {
   "title": "Original Failure Rate Heatmap",
   "type": "heatmap",
   "description": "Heatmap showing distribution of original failure rates across all nodes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "label_replace(original_failure_rate{provider_id=~\"$provider\", node_id=~\"$node\"}, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  {
   "title": "Relative Failure Rate Heatmap",
   "type": "heatmap",
   "description": "Heatmap showing distribution of relative failure rates across all nodes.\nrelative failure rate = original failure rate - subnet failure rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "label_replace(relative_failure_rate{provider_id=~\"$provider\", node_id=~\"$node\"}, \"node_short\", \"$1\", \"node_id\", \"([^-]+)-([^-]+)-([^-]+).*\")",
     "legendFormat": "{{node_short}}"
    }
   ]
  },
  {
   "title": "Node Performance Details",
   "type": "table",
   "description": "Detailed node metrics table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "late{provider_id=~\"$provider\",node_id=~\"$node\"} offset -1d"
    },
    {
     "expr": "relative_failure_rate{provider_id=~\"$provider\",node_id=~\"$node\"} offset -1d"
    }
   ]
  },
  { "title": "Subnet Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Subnet Failure Rates Over Time",
   "type": "timeseries",
   "description": "Subnet failure rates over time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "subnet_failure_rate{subnet_id=~\"$subnet\"}",
     "legendFormat": "{{subnet_id}}"
    }
   ]
  }
 ]
}