- hosts: all
  tasks:
    - name: Ensure systemd-resolved dropin directory exists
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
    - name: Allow resolver to listen on IPv6
      ansible.builtin.copy:
        content: |
          [Resolve]
          DNSStubListenerExtra=[::1]:53
        dest: /etc/systemd/resolved.conf.d/stub-ip6.conf
      notify: Restart systemd-resolved
    - name: Force systemd-resolved to skip the VirtualBox DNS
      ansible.builtin.copy:
        content: |
          [Resolve]
          DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com
        dest: /etc/systemd/resolved.conf.d/forced-dns-servers.conf
      notify: Restart systemd-resolved
    - name: Install net-tools
      ansible.builtin.package:
        name: net-tools
        state: present
  handlers:
    - name: Restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
