- hosts: all
  tasks:
    - name: Ensure systemd-resolved dropin directory exists
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
    - name: Allow resolver to listen on IPv6
      ansible.builtin.copy:
        content: |
          [Resolve]
          DNSStubListenerExtra=[::1]:53
        dest: /etc/systemd/resolved.conf.d/stub-ip6.conf
      notify: Restart systemd-resolved
    - name: Install net-tools
      ansible.builtin.package:
        name: net-tools
        state: present
    - name: Install ufw
      ansible.builtin.package:
        name: ufw
        state: present
    - name: Instruct ufw to allow SSH connections
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp
    - name: Enable firewall
      community.general.ufw:
        state: enabled
  handlers:
    - name: Restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
