{
 "title": "Observability stack github status",
 "description": "This dashboard shows the status of your observability stack and if there are any updates done that can be updated.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Installed and Remote versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Installed commit",
   "type": "table",
   "description": "The version of observability stack that is currently running.",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "targets": [
    { "expr": "git_installed_commit", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "description": "This panel contains the explanation for the installed commit.",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 1 },
   "options": {
    "content": "# Installed and Remote commit(s)\n\nThese panels show the **exact Git commit** (version) of the **IC Observability Stack**. \n\nThere are two versions:\n* **Installed commit** - version of the software that’s currently running.\n* **Remote commit** - most recent version of the software that you can get.\n\nEach commit represents a specific point in the codebase’s history — like a unique “fingerprint” for that version of the application.\n\nKnowing this value is important because it lets us:\n* **Identify which version is deployed** — helpful when debugging or confirming updates.\n* **Report issues accurately** — when you share the commit hash, developers can see the exact code you’re running.\n* **Track deployments** — so we can see when new code goes live and compare environments.\n\nIt is in your best intrest to make these two versions be **equal**.\n\nIf you need to report a problem or behavior difference, include this commit value so the engineering team can reproduce and investigate it precisely.\n"
   }
  },
  {
   "title": "Remote commit",
   "type": "table",
   "description": "This panel shows the most recent remote commit which the latest version of the ic observability stack",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 5 },
   "targets": [
    { "expr": "git_remote_commit", "legendFormat": "__auto" }
   ]
  },
  { "title": "Difference", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "State of the directory",
   "type": "stat",
   "description": "This panel represents the local state of the git directory. It shows if something needs to be commited or the upgrade can be performed cleanly.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "git_local_state", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 15 },
   "options": {
    "content": "# State and difference\n\nThese set of graphs show you the difference between your \nlocal copy of the **IC Observability Stack** and the newest version.\n\n* **Commits ahead** - shows the number of versions *your* local copy \n  is in front of the newest one.\n* **Commits behind** - shows the number of versions *your* local copy\n  is behind of the newest one.\n* **State** - shows whether there are some changes that need to be \n  saved (commited), before the upgrade can happen.\n\nIt is in your best interest to keep the **commits behind** as low as \npossible. To do that, read more in the `UPGRADE_GUIDE.md`.\n\nSometimes, it may not be possible to easily perform the upgrade\ndue to your local state (if it is `Dirty`) or if you have some\ncommits (**commits ahead**) which are not compatible with the changes\ncoming from remote."
   }
  },
  {
   "title": "Commits ahead",
   "type": "stat",
   "description": "If there are any commits ahead there may be issues with updating to the newest version as there may be conflicts with your changes and the ones coming in.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(git_commits_ahead[180d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits behind",
   "type": "stat",
   "description": "How many changes are there to be fetched. It is in your best interest to keep this number as low as possible.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(git_commits_behind[180d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}